name: 'Builds Container Web App'
description: 'Builds a docker based web application'
inputs:
  repository:
    description: "The repository name"
    required: true
  registry:
    description: "The registry to push the image to"
    required: true
    default: "ghcr.io"
  registryUsername:
    description: "The username for the registry"
    required: true
  registryPassword:
    description: "The password for the registry"
    required: true
  tag:
    description: "The tag of the image to build"
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registryUsername }}
        password: ${{ inputs.registryPassword }}

    - name: Lowercase the repo name
      shell: bash
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build container test target
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: ghcr.io/${{ inputs.repository }}:${{ inputs.tag }}-testresults
        file: ./backend/Dockerfile
        context: .
        build-args: BUILDID=${{ github.run_id }}-${{ github.run_attempt }}
        target: test
    - name: Extract test results
      shell: pwsh
      run: |
        #$id=docker images --filter "label=testresults=${{ github.run_id }}-${{ github.run_attempt }}" -q | Select-Object -First 1
        #docker create --name testcontainer $id
        docker create --name testcontainer ghcr.io/${{ inputs.repository }}:${{ inputs.tag }}-testresults
        docker cp testcontainer:/testresults/xunit ./xunit-test-results
        docker cp testcontainer:/testresults/jest ./jest-test-results
        docker rm testcontainer
    - name: Publish Jest test results
      uses: actions/upload-artifact@v3
      with:
        name: jest-test-results
        path: ./jest-test-results
    - name: Publish xUnit test results
      uses: actions/upload-artifact@v3
      with:
        name: xunit-test-results
        path: ./xunit-test-results

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ inputs.repository }}:${{ inputs.tag }}
        file: ./backend/Dockerfile
        context: .
        build-args: BUILDID=${{ github.run_id }}-${{ github.run_attempt }}
        target: final        

    