name: 'Builds Container Web App'
description: 'Builds a docker based web application'
inputs:
  repository:
    description: "The repository name"
    required: true
  tag:
    description: "The tag of the image to build"
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase the repo name
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ inputs.repository }}:${{ inputs.tag }}
        file: ./backend/Dockerfile
        context: .