name: 'Builds Container Web App'
description: 'Builds a docker based web application'
inputs:
  repository:
    description: "The repository name"
    required: true
  registry:
    description: "The registry to push the image to"
    required: true
    default: "ghcr.io"
  registryUsername:
    description: "The username for the registry"
    required: true
  registryPassword:
    description: "The password for the registry"
    required: true
  tag:
    description: "The tag of the image to build"
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registryUsername }}
        password: ${{ inputs.registryPassword }}

    - name: Lowercase the repo name
      shell: bash
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ inputs.repository }}:${{ inputs.tag }}
        file: ./backend/Dockerfile
        context: .

    - name: Extract Jest test results
      shell: bash
      run: |
        TEST_CONTAINER_ID=$(docker create ${{ env.REPOSITORY }}:${{ github.sha }})
        docker cp $TEST_CONTAINER_ID:/testresults/jest ./jest-test-results
        docker rm $TEST_CONTAINER_ID
    - name: Extract xUnit test results
      shell: bash
      run: |
        TEST_CONTAINER_ID=$(docker create ${{ env.REPOSITORY }}:${{ github.sha }})
        docker cp $TEST_CONTAINER_ID:/testresults/xunit ./xunit-test-results
        docker rm $TEST_CONTAINER_ID
    - name: Publish Jest test results
      uses: actions/upload-artifact@v3
      with:
        name: jest-test-results
        path: ./jest-test-results
    - name: Publish xUnit test results
      uses: actions/upload-artifact@v3
      with:
        name: xunit-test-results
        path: ./xunit-test-results