name: Create Azure Resources
on:
  push:
    branches: [ main ]
    paths:
      - "infrastructure/**"
      - ".github/workflows/infrastructure.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "infrastructure/**"
      - ".github/workflows/infrastructure.yml"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 4thelloworlddemo

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    name: Deploy Azure Infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          region: westeurope
          template: repo/infrastructure/webapp.bicep
          parameters: webAppName=pipelineinvaders sku=S1 dockerRegistryUrl=https://ghcr.io dockerRegistryUsername=${{ secrets.PACKAGES_REPOSITORY_OWNER }} dockerRegistryPassword=${{ secrets.PACKAGES_ACCESS_TOKEN }} dockerImage=myrepo/myapp:latest